### ISSUE TITLE
Please explain how to install / use this app

### ISSUE THREAD

**Issue by Hiro3212** [vvviperrr/SimpleRT#12]
Im relativly new to linux and I really need an easy explanation of how I install this program and how I use it.

I have a Huawei p8lite, of which the WiFi isnt working, so I thought, I could use my computers connection on it to install all necessary apps. Because, it isnt rooted, I only can use this one app in the playstore which doesnt work for me, or simpleRT. 

How do I install it? Do I have to download it? where can I execute? I already have the apk from fdroid on my phone, but I dont know how to go on.

Hope somebody with more knowledge than me can explain me.
Thanks

**Comment by vvviperrr** [comment]
>Im relativly new to linux
skype me (vvviperrr00). i will explain in details

**Comment by breversa** [comment]
Same here.

The usage part in the readme is not very helpful :
"Usage:

    run console util as root
    connect your android device
"

What console util ?

**Comment by Hiro3212** [comment]
First you download all depencies. Then you git this folder. Afterwards go into the simple-rt-cli folder and just run 'make'.
Then 'sudo ./simplert'.

This should work.

**Comment by breversa** [comment]
Thank for your fast reply !
I'm actually not familiar with using git and compiling though, and I thought of using SimpleRT on a computer I may not be able to do that anyway. Do you plan any desktop release ?

**Comment by Hiro3212** [comment]
Sorry Im not the developer :) He said its the last thing on his todo list to make a windows release. I also had very low knowledge with linux. You can i.e. use a live distribution, that you can boot from a DVD and run the commands there. If you need I can give you an exact step by step instruction what you need to run to make it work.

**Comment by Hiro3212** [comment]
sudo apt-get update
sudo apt-get install libusb-1.0-0-dev
sudo apt-get install pkg-config
sudo apt-get install git
git clone https://github.com/vvviperrr/SimpleRT
cd SimpleRT/simple-rt-cli
make
sudo ./simplert

==> connect device

**Comment by breversa** [comment]
Great ! Thank you. I think it's worth adding to the wiki/readme in order to help other people too. :-)

**Comment by Hiro3212** [comment]
Thats what I told https://github.com/vvviperrr too, but he said it would be pretty clear for those who know how to build apps in linux.

**Comment by breversa** [comment]
Too much (?) information is better than too little information.

People who know wouldn't care, but people who don't know would appreciate. :-)

**Comment by doronbehar** [comment]
Hello @vvviperrr, I would have contacted you on Skype to ask this question but I don't run nor use such non free software so I think it's best we'll talk here.

I use Lineage OS 14.1 nightly and Arch Linux. I'm confused with the usage of the app and the command `./simple-rt`. I can't make it to actually work and to enable me to load pages with my firefox browser. I have managed to make it to show the 🔑 sign at the top of the screen but I can't actually load pages (when mobile data and WiFi are off of course) in my firefox browser.

These are the questions that popped me:
1. Should I enable tethering in my android device after/before/at all while/after/before running the command `./simple-rt`
2. If I do enable tethering while the device is connected with USB then what interface should I specify when I run the command `./simple-rt -i ??`. Should I choose the interface of the tethering (named `enp0s20u1` on my arch Linux machine)? Or the Ethernet interface `enp0s25`?
3. In general, what exactly is the order of operations that must be taken in order to setup tethering with `./simple-rt`?
